version: '3.7'
networks:
  calc-net:
    driver: bridge
services:
  calc:
    image: iudx/calc-dev:latest
    volumes:
      - ./secrets/all-verticles-configs/config-dev.json:/usr/share/app/secrets/all-verticles-configs/config.json
    ports:
      - "8080:8080"
    networks: 
      - calc-net
