version: '3.7'
networks:
  overlay-net:
    external: true      
    driver: overlay
services:
  calc:
    image: iudx/calc-depl:latest
    volumes:
      - ./secrets/all-verticles-configs/config-depl.json:/usr/share/app/secrets/all-verticles-configs/config.json
    networks: 
      - overlay-net
    depends_on: 
      - "zookeeper"
  
  zookeeper:
    image: zookeeper:latest
    expose:
      - "2181"
    networks:
      - overlay-net

