version: '3.7'
networks:
  overlay-net:
    external: true      
    driver: overlay
services:
  calc:
    image: iudx/calc-depl:latest
    volumes:
      - ./secrets/all-verticles-configs/config-depl.json:/usr/share/app/secrets/all-verticles-configs/config.json
    ports:
      - "8080:8080"
      - "9000:9000"
    networks: 
      - overlay-net
