version: '3.7'
networks:
  calc-net:
    driver: bridge
services:
  calc:
    image: iudx/calc-dev:latest
    volumes:
      - ./secrets/all-verticles-configs/config-dev.json:/usr/share/app/secrets/all-verticles-configs/config.json
      - type: volume
        source: data-volume
        target: /data/
        volume:
          nocopy: true
    ports:
      - "8080:8080"
    networks: 
      - calc-net
    env_file:
      - ./.calc.env
    restart: always
    logging:
       driver: "json-file"
       options:
          max-file: "3"
          max-size: "5m"
    command: bash -c "exec java $$CALC_JAVA_OPTS -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4j2LogDelegateFactory -jar ./fatjar.jar  --host $$(hostname) -c secrets/all-verticles-configs/config.json"

volumes:
  data-volume: