version: "3"

networks:
  default:
    external:
      name: srinskit-net

services:
  adder:
    image: srinskit/calc
    command: -m adder-service
  api-server:
    image: srinskit/calc
    command: -m api-server
    ports:
      - "80:8080"
  zookeeper:
    image: zookeeper
