version: "3.2"

networks:
  default:
    external:
      name: calc-net

services:
  adder:
    image: srinskit/calc
    command: -m adder-service
    depends_on:
      - zookeeper
  api-server:
    image: srinskit/calc
    command: -m api-server
    ports:
      - "80:8080"
    volumes:
      - type: volume
        source: calc-volume
        target: /data
        volume:
          nocopy: true
    depends_on:
      - zookeeper
  zookeeper:
    image: zookeeper
    restart: always

volumes:
  calc-volume:
    external: true